// Generated by CoffeeScript 1.7.1
(function() {
  angular.module("moo.admin.controllers", []).controller("AdminCtrl", [
    "$scope", "$q", "RunningWorkflows", function($scope, $q, RunningWorkflows) {
      var getWorkflowInfo;
      $scope.workflows = {
        instances: [],
        types: []
      };
      $scope.selectedWorkflowInstance = null;
      $scope.deleteWorkflowInstance = function() {
        var wfId;
        wfId = $scope.selectedWorkflowInstance.id;
        return RunningWorkflows.deleteInstance(wfId, getWorkflowInfo());
      };
      $scope.selectedWorkflowType = null;
      $scope.deleteWorkflowType = function() {
        return RunningWorkflows.deleteAllInstancesOfType($scope.selectedWorkflowType).$promise.then(function() {
          return getWorkflowInfo();
        });
      };
      $scope.deleteAllWorkflows = function() {
        var promises, wflow;
        promises = (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = types.length; _i < _len; _i++) {
            wflow = types[_i];
            _results.push(RunningWorkflows.deleteAllInstancesOfType(wflow).$promise);
          }
          return _results;
        })();
        return $q.all(promises).then(function() {
          return getWorkflowInfo();
        });
      };
      getWorkflowInfo = function() {
        $scope.workflows.instances = RunningWorkflows.query();
        return $scope.workflows.instances.$promise.then(function(data) {
          var workflow;
          return $scope.workflows.types = new Set((function() {
            var _i, _len, _results;
            _results = [];
            for (_i = 0, _len = data.length; _i < _len; _i++) {
              workflow = data[_i];
              _results.push(workflow.key);
            }
            return _results;
          })());
        });
      };
      return getWorkflowInfo();
    }
  ]);

}).call(this);

//# sourceMappingURL=admin.map
