// Generated by CoffeeScript 1.7.1
(function() {
  angular.module("moo.builder.controllers", []).controller("WorkflowBuilderCtrl", [
    "$scope", "$routeParams", function($scope, $routeParams) {
      var _ref;
      return $scope.workflowName = (_ref = $routeParams.wflowName) != null ? _ref : "New Workflow";
    }
  ]);

}).call(this);

//# sourceMappingURL=builder.map
