// Generated by CoffeeScript 1.7.1
(function() {
  angular.module("moo.builder.controllers", []).controller("WorkflowBuilderCtrl", [
    "$scope", "$routeParams", "RunningWorkflows", function($scope, $routeParams, RunningWorkflows) {
      return $scope.workflowName = $routeParams.wflowName;
    }
  ]);

}).call(this);

//# sourceMappingURL=builder.map
