// Generated by CoffeeScript 1.7.1
(function() {
  angular.module("moo.controllers", []).controller("TaskListCtrl", [
    "$scope", "Task", function($scope, Task) {
      return $scope.userTasks = Task.userTasks;
    }
  ]).controller("TaskDetailCtrl", [
    "$scope", "$routeParams", "Task", function($scope, $routeParams, Task) {
      return $scope.task = Task.find($routeParams.taskId);
    }
  ]).controller("ActiveWorkflowsCtrl", [
    "$scope", "RunningWorkflow", function($scope, RunningWorkflow) {
      return $scope.statuses = RunningWorkflow.getStatuses();
    }
  ]);

}).call(this);

//# sourceMappingURL=controllers.map
