// Generated by CoffeeScript 1.7.1
(function() {
  angular.module("moo.directives", []).directive("mooNavMenu", function() {
    return {
      restrict: "E",
      scope: {},
      controller: [
        "$scope", "$route", "areas", function($scope, $route, areas) {
          var area;
          $scope.$on("$routeChangeStart", function(evt, newRoute) {
            var tab, _i, _len, _ref, _results;
            _ref = $scope.tabs;
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              tab = _ref[_i];
              _results.push(tab.selected = tab.title === newRoute.provide.area);
            }
            return _results;
          });
          return $scope.tabs = (function() {
            var _i, _len, _results;
            _results = [];
            for (_i = 0, _len = areas.length; _i < _len; _i++) {
              area = areas[_i];
              _results.push({
                title: area.name,
                url: "#" + area.defaultRoute.url,
                selected: area.name === $route.current.provide.area
              });
            }
            return _results;
          })();
        }
      ],
      templateUrl: "partials/nav-menu.html"
    };
  });

}).call(this);

//# sourceMappingURL=directives.map
