// Generated by CoffeeScript 1.7.1
(function() {
  angular.module("moo.services", ["ngResource"]).factory("Task", [
    "$resource", "serviceUrls", function($resource, serviceUrls) {
      return $resource("" + serviceUrls.cowServer + "/tasks/:id", {}, {
        query: {
          isArray: true,
          transformResponse: function(data) {
            return JSON.parse(data).task;
          }
        }
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=services.map
